[package]
name = "reflex"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
mlua = { workspace = true }
notify-rust = "4.17.0"
reflex-core = { path = "../reflex-core" }
serde_json = { workspace = true }
wayland-client = "0.31.15"
wayland-protocols = { version = "0.32.13", features = ["client", "staging"] }
wayland-protocols-plasma = { version = "0.3.12", features = ["client"] }
wayland-protocols-wlr = { version = "0.3.12", features = ["client"] }
x11rb = "0.14.0"
zbus = { version = "5.16.0", features = ["blocking-api"] }
